def fail(exc: Exception):
    raise exc
